// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RemoteDuck")]
[assembly: AssemblyProductAttribute("RemoteDuck")]
[assembly: AssemblyDescriptionAttribute("RemoteDuck is a tool which allows you to show that a remote session is blocked.")]
[assembly: AssemblyVersionAttribute("0.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0";
    }
}
